// <auto-generated />
using GeometriaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Geometria.Migrations
{
    [DbContext(typeof(GeometriaContext))]
    [Migration("20250623220557_AddUsuario")]
    partial class AddUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GeometriaAPI.Models.Circulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double");

                    b.Property<double>("Radio")
                        .HasColumnType("double");

                    b.Property<double>("Volumen")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Circulos");
                });

            modelBuilder.Entity("GeometriaAPI.Models.Cuadrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double");

                    b.Property<double>("Lado")
                        .HasColumnType("double");

                    b.Property<double>("Volumen")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Cuadrados");
                });

            modelBuilder.Entity("GeometriaAPI.Models.Rectangulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ancho")
                        .HasColumnType("double");

                    b.Property<double>("Area")
                        .HasColumnType("double");

                    b.Property<double>("Largo")
                        .HasColumnType("double");

                    b.Property<double>("Volumen")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Rectangulos");
                });

            modelBuilder.Entity("GeometriaAPI.Models.Triangulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double");

                    b.Property<double>("Area")
                        .HasColumnType("double");

                    b.Property<double>("Base")
                        .HasColumnType("double");

                    b.Property<double>("Volumen")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Triangulos");
                });

            modelBuilder.Entity("GeometriaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
